import { registerType } from './index'

registerType({
  type: 'transit_transport',
  title: '转关运输货物申报单',
  description: '海关进出口转关运输货物申报（含过境、中转、直转），包括基本信息、前程提运单、集装箱明细和商品明细',
  field_mappings: [
    // ═══ Section ①: 基本信息 ═══
    { source_key: 'customs_declaration_port', display_label: '申报地海关', section: 'header', required: true, editable: true, field_type: 'text' },
    { source_key: 'entry_exit_port', display_label: '进出口岸', section: 'header', required: true, editable: true, field_type: 'text' },
    { source_key: 'declaration_unit_name', display_label: '申报单位', section: 'header', required: true, editable: true, field_type: 'text' },
    { source_key: 'declaration_unit_credit_code', display_label: '统一社会信用代码', section: 'header', required: false, editable: true, field_type: 'text' },
    { source_key: 'declaration_unit_customs_code', display_label: '海关10位编码', section: 'header', required: false, editable: true, field_type: 'text' },
    { source_key: 'domestic_transport_mode', display_label: '境内运输方式', section: 'transport', required: true, editable: true, field_type: 'select', options: ['铁路运输', '公路运输', '航空运输', '水路运输'] },
    { source_key: 'domestic_transport_tool_name', display_label: '境内运输工具名称', section: 'transport', required: true, editable: true, field_type: 'text' },
    { source_key: 'domestic_transport_tool_id', display_label: '境内运输工具编号', section: 'transport', required: false, editable: true, field_type: 'text' },
    { source_key: 'domestic_transport_voyage', display_label: '境内运输工具航次', section: 'transport', required: false, editable: true, field_type: 'text' },
    { source_key: 'carrier_name', display_label: '承运单位', section: 'party', required: true, editable: true, field_type: 'text' },
    { source_key: 'estimated_arrival_date', display_label: '预计运抵指运地日期', section: 'header', required: true, editable: true, field_type: 'text' },
    { source_key: 'declaration_form_no', display_label: '申报单号', section: 'header', required: false, editable: true, field_type: 'text' },
    { source_key: 'notes', display_label: '备注', section: 'header', required: false, editable: true, field_type: 'text' },

    // ═══ Section ②: 前程提运单信息 ═══
    { source_key: 'transport_mode', display_label: '运输方式', section: 'transport', required: true, editable: true, field_type: 'select', options: ['水路运输', '铁路运输', '公路运输', '航空运输'] },
    { source_key: 'vessel_no', display_label: '船舶编号', section: 'transport', required: false, editable: true, field_type: 'text' },
    { source_key: 'vessel_name_en', display_label: '船舶英文名', section: 'transport', required: true, editable: true, field_type: 'text' },
    { source_key: 'voyage_no', display_label: '航次号', section: 'transport', required: true, editable: true, field_type: 'text' },
    { source_key: 'bill_of_lading_no', display_label: '提单号', section: 'transport', required: true, editable: true, field_type: 'text' },
    { source_key: 'entry_exit_date', display_label: '进出境日期', section: 'header', required: false, editable: true, field_type: 'text' },
    { source_key: 'bl_package_count', display_label: '件数', section: 'package', required: true, editable: true, field_type: 'number' },
    { source_key: 'bl_gross_weight', display_label: '重量(KG)', section: 'package', required: true, editable: true, field_type: 'number' },
    { source_key: 'previous_declaration_no', display_label: '前程报关单号', section: 'header', required: false, editable: true, field_type: 'text' },
    { source_key: 'consignee_name', display_label: '收货人', section: 'party', required: true, editable: true, field_type: 'text' },
  ],
  cargo_column_mappings: [
    // ═══ Section ④: 商品明细 ═══
    { source_key: 'seq_no', display_label: '#', section: 'cargo', required: false, editable: false, field_type: 'readonly' },
    { source_key: 'hs_code', display_label: '商品编码', section: 'cargo', required: true, editable: true, field_type: 'text' },
    { source_key: 'cargo_name_spec', display_label: '品名及规格', section: 'cargo', required: true, editable: true, field_type: 'text' },
    { source_key: 'packaging', display_label: '包装', section: 'cargo', required: false, editable: true, field_type: 'text' },
    { source_key: 'package_count', display_label: '件数', section: 'cargo', required: true, editable: true, field_type: 'number' },
    { source_key: 'quantity', display_label: '数量', section: 'cargo', required: false, editable: true, field_type: 'number' },
    { source_key: 'unit', display_label: '单位', section: 'cargo', required: true, editable: true, field_type: 'select', options: ['个', '台', '套', '千克', '吨', '米', '立方米', '升', '件', '箱', '桶', '袋', '包'] },
    { source_key: 'gross_weight', display_label: '重量(KG)', section: 'cargo', required: true, editable: true, field_type: 'number' },
    { source_key: 'total_price', display_label: '成交价格', section: 'cargo', required: true, editable: true, field_type: 'number' },
    { source_key: 'currency_code', display_label: '币制', section: 'cargo', required: true, editable: true, field_type: 'select', options: ['人民币', '美元', '欧元', '日元', '港币', '英镑', '韩元', '澳元'] },
    { source_key: 'container_numbers', display_label: '所在集装箱号', section: 'cargo', required: false, editable: true, field_type: 'text' },
  ],
  container_column_mappings: [
    // ═══ Section ③: 集装箱明细 ═══
    { source_key: 'container_no', display_label: '集装箱号', section: 'cargo', required: true, editable: true, field_type: 'text' },
    { source_key: 'container_size', display_label: '尺寸', section: 'cargo', required: true, editable: true, field_type: 'select', options: ['20尺', '40尺', '45尺', '其他'] },
    { source_key: 'container_package_count', display_label: '件数', section: 'cargo', required: false, editable: true, field_type: 'number' },
    { source_key: 'container_weight', display_label: '重量(KG)', section: 'cargo', required: false, editable: true, field_type: 'number' },
    { source_key: 'container_transport_tool_id', display_label: '运输工具编号', section: 'cargo', required: false, editable: true, field_type: 'text' },
    { source_key: 'container_transport_tool_name', display_label: '运输工具名称', section: 'cargo', required: true, editable: true, field_type: 'text' },
    { source_key: 'container_transport_tool_weight', display_label: '运输工具重量(KG)', section: 'cargo', required: false, editable: true, field_type: 'number' },
    { source_key: 'customs_lock_count', display_label: '关锁个数', section: 'cargo', required: true, editable: true, field_type: 'number' },
    { source_key: 'customs_lock_no', display_label: '关锁号', section: 'cargo', required: true, editable: true, field_type: 'text' },
    { source_key: 'seal_no', display_label: '封志号', section: 'cargo', required: false, editable: true, field_type: 'text' },
  ],
  validation_rules: [
    { type: 'required', message: '申报地海关是必填项' },
    { type: 'required', message: '进出口岸是必填项' },
    { type: 'required', message: '申报单位是必填项' },
    { type: 'required', message: '境内运输方式是必填项' },
    { type: 'required', message: '境内运输工具名称是必填项' },
    { type: 'required', message: '承运单位是必填项' },
    { type: 'required', message: '预计运抵指运地日期是必填项' },
    { type: 'required', message: '提运单运输方式是必填项' },
    { type: 'required', message: '船舶英文名是必填项' },
    { type: 'required', message: '航次号是必填项' },
    { type: 'required', message: '提单号是必填项' },
    { type: 'required', message: '提运单件数是必填项' },
    { type: 'required', message: '提运单重量是必填项' },
    { type: 'required', message: '收货人是必填项' },
  ],
})
